[functions]
  directory = "src/functions"
  node_bundler = "esbuild"

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "https://singlekey.app/*"
  to = "https://www.singlekey.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[dev]
  framework = "vite"
  targetPort = 5173
  autoLaunch = false
  edge_functions = false
